// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DButton: typeof import('vue-devui/button/index.es.js')['Button']
    DContent: typeof import('vue-devui/content/index.es.js')['Content']
    DFooter: typeof import('vue-devui/footer/index.es.js')['Footer']
    DHeader: typeof import('vue-devui/header/index.es.js')['Header']
    DLayout: typeof import('vue-devui/layout/index.es.js')['Layout']
    DPanel: typeof import('vue-devui/panel/index.es.js')['Panel']
    DSplitter: typeof import('vue-devui/splitter/index.es.js')['Splitter']
    DSplitterPane: typeof import('vue-devui/splitter-pane/index.es.js')['SplitterPane']
    Home: typeof import('./src/components/Home.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
